services:
  jog-test:
    build:
      context: .
      dockerfile: Dockerfile
    image: jog-test
    tty: true
    privileged: true
    # command: bash -c "python3 inputstest.py"
    command: bash -c "python3 pygametest.py"
    # command: bash -c "./entrypoint_jog_test.sh"
    volumes:
      - "/dev/input:/dev/input"
      - "./:/workspace"
    devices:
      - "/dev/input:/dev/input"